version: "3.9"
services:
  nifi:
    image: apache/nifi:1.20.0
    container_name: nifi_cont
    depends_on:
     - nifi-registry
    networks:
      - docker-nifi-postgres
    hostname: nifi
    ports:
      - 8080:8080
    environment:
      - NIFI_SENSITIVE_PROPS_KEY=1234567890qaz
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_ELECTION_MAX_WAIT=1 min
      - WORKDIR=/opt/nifi/nifi-current
    volumes:
      - ../bin/nifi/drivers/:/opt/nifi/nifi-current/drivers # Монтируем папку с драйверами для подключения к БД
      - ../bin/nifi/python_scripts/:/opt/nifi/nifi-current/python_scripts
      - ../bin/nifi/bin/:/opt/nifi/nifi-current/bin/
      - C:\Users\Professional\AppData\Local\Programs\Python\Python311:/opt/nifi/nifi-current/python311
      
  postgres:
    container_name: postgres_container
    image: postgres:13.3
    environment:
      POSTGRES_DB: "dwh"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin1qaz"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../bin/postgresDb/AdventureWorks/:/docker-entrypoint-initdb.d/ # располагаем скрипт для инициализации БД
      - ../bin/postgresDb/:/var/lib/postgresql/data # позволяет хранить данные в папке проекта
    ports:
      - "5433:5432"
    networks:
      - docker-nifi-postgres

networks:
  docker-nifi-postgres:
    driver: bridge
